"""Add assigned_at to Lead

Revision ID: 27282bb59afc
Revises: fab492d902d9
Create Date: 2025-08-01 23:55:16.914045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27282bb59afc'
down_revision = 'fab492d902d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_column('assigned_at')

    # ### end Alembic commands ###
