"""Add city and state columns

Revision ID: 5df2a101fcb2
Revises: 3639b5ccd113
Create Date: 2025-07-13 11:42:12.798209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5df2a101fcb2'
down_revision = '3639b5ccd113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_column('course')

    # ### end Alembic commands ###
